name: library_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^1.4.2
  cached_network_image: ^3.2.1
  font_awesome_flutter: ^10.2.1
  flutter_swiper_view: ^1.1.8
  flutter_rating_bar: ^4.0.1
  json_annotation: ^4.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  stream_transform: ^2.1.0
  provider: ^6.0.4
  intl: ^0.17.0
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  json_serializable:
  build_runner:
  hive_generator:
  retrofit_generator:

  
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
